services:
    ger.magicogp.listener:
        class: ger\magicogp\event\main_listener
        arguments:
            - '@log'
            - '@config'
            - '@config_text'
            - '@language'
        tags:
            - { name: event.listener }